### PR TITLE
FIXME needs tuning

### PR DESCRIPTION
**Pull request by ZachBeta**
this is a bulk copy
it needs some language tuning since it's more for an OSS project, not a community group
also there's a contact point under `##Enforcement` that we'd need to make more concrete

### CODE REVIEW

**Comment by ZachBeta** [comment]
Railsconf 2017 has a pretty short anti harassment policy,
that may be relevant to our org a bit more since it's event oriented and not code oriented
https://railsconf.com/policies

**Comment by jhirbour** [comment]
For reference: the current version of the contributor covant is:  http://contributor-covenant.org/version/1/4/code_of_conduct.md

**Comment by ZachBeta** [comment]
Yeah that's what I copypasta'd into the pr.
Any ideas on tweaks to better fit our event vs code focus?

**Comment by jhirbour** [comment]
Ah I mis-read, I thought you ported in the railsconf one.

**Comment by danbernier** [comment]
We adopted the one we have as a stop-measure gap, and I've always wanted to improve it.

I think ours should cover our events, but de-emphasize the role of event staff (eg "if you are harassed, here is the phone # for the organizer"). It should probably cover slack & meetup comments, too, since we're an online community.

**Comment by sukima** [comment]
Here is a **general** code-of-conduct example that covers a community (conferences, events, github comments, Slack channels, etc.): https://emberjs.com/guidelines/

Good for reference / ideas.

**Comment by ZachBeta** [comment]
@treznick could you put your most recent draft up in whatever form it currently is?
we can probably finish the last 20% as a group

**Comment by treznick** [comment]
@ZachBeta yes, I can try to write that up this weekend. If not then on
monday.

**Comment by ZachBeta** [comment]
Maybe bring it to hack night?

**Comment by Quinncuatro** [comment]
Closing this due to new changes being proposed in a new PR.

**Pull request closed without merging**
